### PR TITLE
fix issue by default bor RPC is to listen localhost only

### PR DESCRIPTION
**Pull request by perfectstake**

### CODE REVIEW

**Comment by vcastellm** [comment]
The goal of using `0.0.0.0` is to listen in all interfaces, what's your use case?

**Comment by perfectstake** [comment]
Hello @vcastellm, I believe the geth functionality is required on `localhost` to listen all interfaces? and this is perfectly solved by 127.0.0.1 address as the default listening. Exposing the bor RPC port to the externals by default is major security risk. @delroybosco has the full report of that.

**Review by vcastellm — APPROVED** [review]
Thanks for noticing this @perfectstake, also remember to secure your deployments using a firewall or SG rules.

**Comment by bogerv** [comment]
Hi, if the internal bor of the container only listens to 127.0.0.1
`[root@bc-gcp-sg-test-node polygon_data]# docker exec -it c52feabe89aa sh
/ # netstat -antp | grep 8545
tcp        0      0 127.0.0.1:8545          0.0.0.0:*               LISTEN      45/bor`

JSONRPC for bor cannot be accessed outside the container using mapped port 8547

`[root@bc-gcp-sg-test-node polygon_data]# docker ps
CONTAINER ID   IMAGE                                   COMMAND                PORTS                                                                                                                  NAMES
3bd42af4ce30   maticnetwork/heimdall:v0.2.4            "bash -c '\n  if [ ! …"   0.0.0.0:1317->1317/tcp, :::1317->1317/tcp, 0.0.0.0:26656-26657->26656-26657/tcp, :::26656-26657->26656-26657/tcp       heimdall0
c52feabe89aa   maticnetwork/bor:master                 "sh -c '\n  cd /root …"   8547/tcp, 30303/tcp, 30303/udp, 0.0.0.0:8547->8545/tcp, :::8547->8545/tcp, 0.0.0.0:8549->8546/tcp, :::8549->8546/tcp   bor0`

And using telnet 0.0.0.0 8547 will return a failure

`Trying 0.0.0.0...
Connected to 0.0.0.0.
Escape character is '^]'.
Connection closed by foreign host.`

What should we do if we need to use JSONRPC?
Do I need to manually change the start.sh
--http --http.addr '127.0.0.1'.
Change it to
--http --http.addr '0.0.0.0' (translator's note: "0.0.0.0")

**Pull request merged**
